# Generated by Django 4.2.5 on 2024-02-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_tag_remove_job_tags_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='dateUpdated',
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='FormApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('pName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lastCompany', models.CharField(max_length=100)),
                ('lastJobTitle', models.CharField(max_length=100)),
                ('lastDateEmployed', models.DateField()),
                ('contactSuper', models.BooleanField(default=False)),
                ('superName', models.CharField(max_length=100)),
                ('superTitle', models.CharField(max_length=100)),
                ('superContact', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('dateOfGrad', models.DateField()),
                ('languages', models.CharField(max_length=200)),
                ('citizenship', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('forJob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='careers.job')),
            ],
        ),
    ]
