# Generated by Django 4.2.5 on 2024-02-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_remove_job_dateupdated_alter_job_id_formapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapp',
            old_name='date',
            new_name='dateOfBirth',
        ),
    ]
