# Generated by Django 4.2.5 on 2024-02-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_rename_date_formapp_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapp',
            name='dateOfBirth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formapp',
            name='dateOfGrad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formapp',
            name='lastDateEmployed',
            field=models.CharField(max_length=100),
        ),
    ]
