# Generated by Django 4.2.5 on 2024-02-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_alter_formapp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapp',
            name='forJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.job'),
        ),
    ]
