# Generated by Django 4.2.5 on 2024-02-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_alter_formapp_forjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='Product managers are essential to the upkeep of the team.'),
            preserve_default=False,
        ),
    ]
